export const originalData = {
  id: null,
  caseId: "101010",
  gongsaNo: "422001",
  nodes: [
    {
      id: "K/L",
      type: "cpmMain",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 1,
        lst: 1,
        blockName: "K/L",
        startDate: "2023-07-18",
        endDate: "2023-07-18",
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "L/C",
      type: "cpmEnd",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 1,
        lst: 1,
        blockName: "L/C",
        startDate: "2023-07-25",
        endDate: "2023-07-25",
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "A11C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "A11C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "E11C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "E11C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "E12C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "E12C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "M11C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "M11C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "F11C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "F11C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "F12C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "F12C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "W11C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "W11C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "H11C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "H11C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "H12C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "H12C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "H21C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "H21C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "H31C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "H31C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
    {
      id: "H41C",
      type: "cpm",
      position: {
        x: 0.0,
        y: 0.0,
      },
      data: {
        est: 0,
        lst: 0,
        blockName: "H41C",
        startDate: null,
        endDate: null,
        criticalPath: false,
      },
      width: 70,
      height: 55,
      selected: false,
      positionAbsolute: {
        x: 0.0,
        y: 0.0,
      },
      dragging: false,
    },
  ],
  edges: null,
  createUser: null,
  createdAt: null,
  updateUser: null,
  updatedAt: null,
};
