export const initialNodes = [
  {
    id: "K/L",
    type: "cpmMain",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 1,
      lst: 1,
      blockName: "K/L",
      startDate: "2023-07-18 00:00:00",
      endDate: "2023-07-18 00:00:00",
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "L/C",
    type: "cpmEnd",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 1,
      lst: 1,
      blockName: "K/L",
      startDate: "2023-07-25 00:00:00",
      endDate: "2023-07-25 00:00:00",
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "K/L",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "K/L",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    width: 70,
    height: 55,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
];
export const initialEdges = [];
