// // export const initialNodes = [
// //   {
// //     id: "K/L",
// //     type: "cpmMain",
// //     deletable: false,
// //     position: {
// //       x: 0,
// //       y: 0,
// //     },
// //     data: {
// //       est: 1,
// //       lst: 1,
// //       blockName: "K/L",
// //       startDate: "2023-07-01",
// //       endDate: "2023-07-01",
// //     },
// //     width: 70,
// //     height: 55,
// //     selected: false,
// //     positionAbsolute: {
// //       x: 0,
// //       y: 0,
// //     },
// //     dragging: false,
// //     // style: {
// //     //   // background: "#45AA52",
// //     //   // width: 150,
// //     //   color: "#fff",
// //     //   fontSize: "4px",
// //     //   fontFamily: "Helvetica",
// //     //   boxShadow: "5px 5px 5px 0px rgba(0,0,0,.10)",
// //     // },
// //   },
// //   {
// //     id: "L/C",
// //     type: "cpmEnd",
// //     position: {
// //       x: 0,
// //       y: 0,
// //     },
// //     data: {
// //       est: 1,
// //       lst: 1,
// //       blockName: "L/C",
// //       startDate: "2023-07-01",
// //       endDate: "2023-07-01",
// //     },
// //     width: 70,
// //     height: 55,
// //     selected: false,
// //     positionAbsolute: {
// //       x: 0,
// //       y: 0,
// //     },
// //     dragging: false,
// //   },
// // ];

// // export const initialNodes = [
// //   {
// //     id: "K/L",
// //     type: "cpmMain",
// //     deletable: false,
// //     position: {
// //       x: 0,
// //       y: 0,
// //     },
// //     data: {
// //       est: 1,
// //       lst: 1,
// //       blockName: "K/L",
// //       startDate: "2023-06-30",
// //       endDate: "2023-06-30",
// //     },
// //     width: 70,
// //     height: 55,
// //     selected: false,
// //     positionAbsolute: {
// //       x: 0,
// //       y: 0,
// //     },
// //     dragging: false,
// //     // style: {
// //     //   // background: "#45AA52",
// //     //   // width: 150,
// //     //   color: "#fff",
// //     //   fontSize: "4px",
// //     //   fontFamily: "Helvetica",
// //     //   boxShadow: "5px 5px 5px 0px rgba(0,0,0,.10)",
// //     // },
// //   },
// //   {
// //     id: "L/C",
// //     type: "cpmEnd",
// //     position: {
// //       x: 0,
// //       y: 0,
// //     },
// //     data: {
// //       est: 1,
// //       lst: 1,
// //       blockName: "L/C",
// //       startDate: "2023-07-05",
// //       endDate: "2023-07-05",
// //     },
// //     width: 70,
// //     height: 55,
// //     selected: false,
// //     positionAbsolute: {
// //       x: 0,
// //       y: 0,
// //     },
// //     dragging: false,
// //   },
// //   {
// //     id: "Block",
// //     type: "cpm",
// //     position: {
// //       x: 0,
// //       y: 0,
// //     },
// //     data: {
// //       est: 1,
// //       lst: 1,
// //       blockName: "Block",
// //       startDate: "2023-07-01",
// //       endDate: "2023-07-01",
// //     },
// //     width: 70,
// //     height: 55,
// //     selected: false,
// //     positionAbsolute: {
// //       x: 0,
// //       y: 0,
// //     },
// //     dragging: false,
// //   },
// //   {
// //     id: "Event",
// //     type: "cpmEvent",
// //     position: {
// //       x: 0,
// //       y: 0,
// //     },
// //     data: {
// //       est: 1,
// //       lst: 1,
// //       blockName: "Event",
// //       startDate: "2023-07-01",
// //       endDate: "2023-07-01",
// //     },
// //     width: 70,
// //     height: 55,
// //     selected: false,
// //     positionAbsolute: {
// //       x: 0,
// //       y: 0,
// //     },
// //     dragging: false,
// //   },
// // ];

// // export const initialEdges = [
// //   // {
// //   //   id: "e1-3",
// //   //   source: "node-1",
// //   //   target: "node-3",
// //   //   label: "8",
// //   // },
// // ];

// export const initialNodes = [
//   {
//     id: "A11C",
//     type: "cpm",
//     position: {
//       x: 0,
//       y: 0,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "A11C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 150,
//       height: 400,
//     },
//     width: 152,
//     height: 402,
//     selected: false,
//     positionAbsolute: {
//       x: 0,
//       y: 0,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "E11C",
//     type: "cpm",
//     position: {
//       x: 165.264739884393,
//       y: 0,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "E11C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 800,
//       height: 90,
//     },
//     width: 802,
//     height: 92,
//     selected: false,
//     positionAbsolute: {
//       x: 165.264739884393,
//       y: 0,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "E12C",
//     type: "cpm",
//     position: {
//       x: 163.24161849710993,
//       y: 104.5549132947977,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "E12C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 240,
//       height: 80,
//     },
//     width: 242,
//     height: 82,
//     selected: false,
//     positionAbsolute: {
//       x: 163.24161849710993,
//       y: 104.5549132947977,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "M11C",
//     type: "cpm",
//     position: {
//       x: 166.44624277456643,
//       y: 217.3248554913295,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "M11C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 180,
//       height: 180,
//     },
//     width: 182,
//     height: 182,
//     selected: false,
//     positionAbsolute: {
//       x: 166.44624277456643,
//       y: 217.3248554913295,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "F11C",
//     type: "cpm",
//     position: {
//       x: 419.0890173410403,
//       y: 105.30173410404628,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "F11C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 240,
//       height: 80,
//     },
//     width: 242,
//     height: 82,
//     selected: false,
//     positionAbsolute: {
//       x: 419.0890173410403,
//       y: 105.30173410404628,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "F12C",
//     type: "cpm",
//     position: {
//       x: 881.5884393063583,
//       y: 208.36300578034684,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "F12C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 80,
//       height: 100,
//     },
//     width: 82,
//     height: 102,
//     selected: false,
//     positionAbsolute: {
//       x: 881.5884393063583,
//       y: 208.36300578034684,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "W11C",
//     type: "cpm",
//     position: {
//       x: 680.9109826589595,
//       y: 105.30173410404625,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "W11C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 280,
//       height: 80,
//     },
//     width: 282,
//     height: 82,
//     selected: false,
//     positionAbsolute: {
//       x: 680.9109826589595,
//       y: 105.30173410404625,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "H11C",
//     type: "cpm",
//     position: {
//       x: 469.77803468208106,
//       y: 328.6011560693642,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "H11C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 480,
//       height: 64,
//     },
//     width: 482,
//     height: 66,
//     selected: true,
//     positionAbsolute: {
//       x: 469.77803468208106,
//       y: 328.6011560693642,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "H12C",
//     type: "cpm",
//     position: {
//       x: 972.6057803468209,
//       y: -2.987283236994216,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "H12C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 150,
//       height: 400,
//     },
//     width: 152,
//     height: 402,
//     selected: false,
//     positionAbsolute: {
//       x: 972.6057803468209,
//       y: -2.987283236994216,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "H21C",
//     type: "cpm",
//     position: {
//       x: 562.0716763005781,
//       y: 210.60346820809247,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "H21C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 300,
//       height: 100,
//     },
//     width: 302,
//     height: 102,
//     selected: false,
//     positionAbsolute: {
//       x: 562.0716763005781,
//       y: 210.60346820809247,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "H31C",
//     type: "cpm",
//     position: {
//       x: 368.8624277456649,
//       y: 217.32485549132946,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "H31C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 80,
//       height: 180,
//     },
//     width: 82,
//     height: 182,
//     selected: false,
//     positionAbsolute: {
//       x: 368.8624277456649,
//       y: 217.32485549132946,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
//   {
//     id: "H41C",
//     type: "cpm",
//     position: {
//       x: 469.90057803468216,
//       y: 212.09710982658962,
//     },
//     data: {
//       est: 0,
//       lst: 0,
//       blockName: "H41C",
//       startDate: null,
//       endDate: null,
//       criticalPath: false,
//       width: 80,
//       height: 100,
//     },
//     width: 82,
//     height: 102,
//     selected: false,
//     positionAbsolute: {
//       x: 469.90057803468216,
//       y: 212.09710982658962,
//     },
//     dragging: false,
//     targetPosition: "top",
//     sourcePosition: "bottom",
//   },
// ];

// export const initialEdges = [
//   // {
//   //   id: "e1-3",
//   //   source: "node-1",
//   //   target: "node-3",
//   //   label: "8",
//   // },
// ];

// export const initialNodes = [
//   {
//     id: "K/L",
//     type: "cpmMain",
//     deletable: false,
//     position: {
//       x: 0,
//       y: 0,
//     },
//     data: {
//       est: 1,
//       lst: 1,
//       blockName: "K/L",
//       startDate: "2023-07-01",
//       endDate: "2023-07-01",
//     },
//     width: 70,
//     height: 55,
//     selected: false,
//     positionAbsolute: {
//       x: 0,
//       y: 0,
//     },
//     dragging: false,
//     // style: {
//     //   // background: "#45AA52",
//     //   // width: 150,
//     //   color: "#fff",
//     //   fontSize: "4px",
//     //   fontFamily: "Helvetica",
//     //   boxShadow: "5px 5px 5px 0px rgba(0,0,0,.10)",
//     // },
//   },
//   {
//     id: "L/C",
//     type: "cpmEnd",
//     position: {
//       x: 0,
//       y: 0,
//     },
//     data: {
//       est: 1,
//       lst: 1,
//       blockName: "L/C",
//       startDate: "2023-07-01",
//       endDate: "2023-07-01",
//     },
//     width: 70,
//     height: 55,
//     selected: false,
//     positionAbsolute: {
//       x: 0,
//       y: 0,
//     },
//     dragging: false,
//   },
// ];

// export const initialNodes = [
//   {
//     id: "K/L",
//     type: "cpmMain",
//     deletable: false,
//     position: {
//       x: 0,
//       y: 0,
//     },
//     data: {
//       est: 1,
//       lst: 1,
//       blockName: "K/L",
//       startDate: "2023-06-30",
//       endDate: "2023-06-30",
//     },
//     width: 70,
//     height: 55,
//     selected: false,
//     positionAbsolute: {
//       x: 0,
//       y: 0,
//     },
//     dragging: false,
//     // style: {
//     //   // background: "#45AA52",
//     //   // width: 150,
//     //   color: "#fff",
//     //   fontSize: "4px",
//     //   fontFamily: "Helvetica",
//     //   boxShadow: "5px 5px 5px 0px rgba(0,0,0,.10)",
//     // },
//   },
//   {
//     id: "L/C",
//     type: "cpmEnd",
//     position: {
//       x: 0,
//       y: 0,
//     },
//     data: {
//       est: 1,
//       lst: 1,
//       blockName: "L/C",
//       startDate: "2023-07-05",
//       endDate: "2023-07-05",
//     },
//     width: 70,
//     height: 55,
//     selected: false,
//     positionAbsolute: {
//       x: 0,
//       y: 0,
//     },
//     dragging: false,
//   },
//   {
//     id: "Block",
//     type: "cpm",
//     position: {
//       x: 0,
//       y: 0,
//     },
//     data: {
//       est: 1,
//       lst: 1,
//       blockName: "Block",
//       startDate: "2023-07-01",
//       endDate: "2023-07-01",
//     },
//     width: 70,
//     height: 55,
//     selected: false,
//     positionAbsolute: {
//       x: 0,
//       y: 0,
//     },
//     dragging: false,
//   },
//   {
//     id: "Event",
//     type: "cpmEvent",
//     position: {
//       x: 0,
//       y: 0,
//     },
//     data: {
//       est: 1,
//       lst: 1,
//       blockName: "Event",
//       startDate: "2023-07-01",
//       endDate: "2023-07-01",
//     },
//     width: 70,
//     height: 55,
//     selected: false,
//     positionAbsolute: {
//       x: 0,
//       y: 0,
//     },
//     dragging: false,
//   },
// ];

// export const initialEdges = [
//   // {
//   //   id: "e1-3",
//   //   source: "node-1",
//   //   target: "node-3",
//   //   label: "8",
//   // },
// ];

// export const initialNodes = [
//   {
//     id: "2",
//     data: {
//       blockName: "group",
//     },
//     type: "cpm",
//     position: { x: 0, y: 0 },
//     className: "light",
//     style: { backgroundColor: "#eee", width: "50%", height: "100%" },
//     draggable: false,
//   },
//   {
//     id: "A11C",
//     type: "cpm",
//     position: {
//       x: 0,
//       y: 0,
//     },
//     style: {
//       backgroundColor: "#fff",
//       width: 150,
//       height: 400,
//     },
//     data: {
//       blockName: "A11C",
//     },
//     width: 150,
//     height: 400,
//     parentNode: "2",
//     extent: "parent",
//   },
//   {
//     id: "E11C",
//     type: "cpm",
//     position: {
//       x: 153,
//       y: 2,
//     },
//     style: {
//       backgroundColor: "#fff",
//       width: 800,
//       height: 90,
//     },
//     data: {
//       blockName: "E11C",
//     },
//     width: 800,
//     height: 90,
//     parentNode: "2",
//     extent: "parent",
//   },

//   {
//     id: "3",
//     data: {
//       blockName: "group",
//     },
//     type: "cpm",
//     position: { x: "800", y: 0 },
//     className: "light",
//     style: { backgroundColor: "#eee", width: "50%", height: "50%" },
//   },
//   {
//     id: "3-A11C",
//     type: "cpm",
//     position: {
//       x: 0,
//       y: 0,
//     },
//     style: {
//       backgroundColor: "#fff",
//       width: 150,
//       height: 400,
//     },
//     data: {
//       blockName: "3-A11C",
//     },
//     width: 150,
//     height: 400,
//     parentNode: "3",
//     extent: "parent",
//   },
// ];

export const initialEdges = [
  // {
  //   id: "e1-3",
  //   source: "node-1",
  //   target: "node-3",
  //   label: "8",
  // },
];

export const initialNodes = [
  {
    id: "B201",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "B201",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 340,
      height: 80,
    },
    width: 340,
    height: 80,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "B301",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "B301",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 160,
      height: 100,
    },
    width: 160,
    height: 100,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "B401",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "B401",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 300,
      height: 40,
    },
    width: 300,
    height: 40,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "B402",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "B402",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 80,
      height: 0,
    },
    width: 80,
    height: 0,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "B403",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "B403",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 200,
      height: 40,
    },
    width: 200,
    height: 40,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "A11C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "A11C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 140,
      height: 100,
    },
    width: 140,
    height: 100,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "E11C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "E11C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 220,
      height: 100,
    },
    width: 220,
    height: 100,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "E12C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "E12C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 240,
      height: 100,
    },
    width: 240,
    height: 100,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "M11C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "M11C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 200,
      height: 100,
    },
    width: 200,
    height: 100,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "F11C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "F11C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 80,
      height: 100,
    },
    width: 80,
    height: 100,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "F12C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "F12C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 80,
      height: 100,
    },
    width: 80,
    height: 100,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "W11C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "W11C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 260,
      height: 20,
    },
    width: 260,
    height: 20,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "H11C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "H11C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 160,
      height: 40,
    },
    width: 160,
    height: 40,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "H12C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "H12C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 400,
      height: 40,
    },
    width: 400,
    height: 40,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "H21C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "H21C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 360,
      height: 40,
    },
    width: 360,
    height: 40,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "H31C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "H31C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 200,
      height: 60,
    },
    width: 200,
    height: 60,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
  {
    id: "H41C",
    type: "cpm",
    position: {
      x: 0,
      y: 0,
    },
    data: {
      est: 0,
      lst: 0,
      blockName: "H41C",
      startDate: null,
      endDate: null,
      criticalPath: false,
    },
    style: {
      width: 100,
      height: 60,
    },
    width: 100,
    height: 60,
    selected: false,
    positionAbsolute: {
      x: 0,
      y: 0,
    },
    dragging: false,
  },
];
